name: Run nitpick to sync CI configs

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

env:
  HATCH_VERSION: "1.15.1"

jobs:
  nitpick:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.14'

      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          version: "${{ env.HATCH_VERSION }}"

      - name: Run nitpick
        run: hatch run pre-commit:run nitpick --all || true
        shell: bash

      - name: Run pre-commit
        shell: bash
        run: |
          n=0
          while [[ $n -lt 5 ]] && ! hatch run pre-commit:run; do
            ((n++))
          done
          exit $?

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "ci(nitpick): Sync CI configs"
          title: "ci(nitpick): Sync CI configs"
          body: "Automated run of nitpick fix."
          branch: "nitpick"
          base: ${{ github.ref_name }}
          labels: "nitpick"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
