name: Run nitpick to sync CI configs

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  nitpick:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install nitpick
        run: pipx install nitpick

      - name: Run nitpick
        run: nitpick fix || true
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "ci(nitpick): Sync CI configs"
          title: "ci(nitpick): Sync CI configs"
          body: "Automated run of nitpick fix."
          branch: "nitpick"
          base: ${{ github.ref_name }}
          labels: "nitpick"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
