name: Update .pre-commit-config.yaml

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

env:
  HATCH_VERSION: "1.16.2"

jobs:
  update-pre-commit-config:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.14'

      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          version: "${{ env.HATCH_VERSION }}"

      - name: Update .pre-commit-config.yaml
        run: hatch run pre-commit:pre-commit autoupdate --freeze

      - name: Run pre-commit
        run: hatch run pre-commit:run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          commit-message: "chore(deps): Update .pre-commit-config.yaml"
          title: "chore(deps): Update .pre-commit-config.yaml"
          body: "Automated update of .pre-commit-config.yaml via scheduled workflow."
          branch: "update/pre-commit-config-yaml"
          base: ${{ github.ref_name }}
          labels: "update"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
